### ISSUE TITLE
"fly apps create" not working correctly anymore

### ISSUE THREAD

**Issue by marko-x** [remix-run/blues-stack#138]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- Follow the steps in the readme.
- "fly apps create [...]" not working correctly. 

It creates an an app on fly.io but without an ip address. The created app has a orange wrench symbol. The app missing configurations.

### Expected Behavior

Following the readme should lead you to have a running app.

### Actual Behavior

Follow the readme will not working anymore, because fly.io app (remix) will not have an IP Address.

**Comment by pyyding** [comment]
The problem is caused because a missing `FLY_REGION` env variable in the github deploy action. For time being I suggest you to edit your deployment script to include it manually.

To both `🚀 Deploy Staging` and `🚀 Deploy Production` steps under the `env` section you need to add your database region. 

You can find the db code when you create the db or
1) Go to Fly.io dashboard 
2) Open your Postgres instance
3) Open the Machines tab
4) Copy the region code

The `deploy.yml` env section should look something like this:
```
        env:
          FLY_REGION: "ams"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

**Comment by machour** [comment]
@pyyding do you want to submit a PR to fix this?

**Comment by MichaelDeBoey** [comment]
@marko-x @pyyding Will this be fixed if you apply the same changes as I did in #178?
